-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN "cachedLevel" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN "cachedWidthMeters" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN "cachedHeightMeters" DOUBLE PRECISION NOT NULL DEFAULT 0;
